Repository cmu-db/bustub, pull requests merged in 2019-11, with the labels that each got.

#38 Fix Schema::GetColIdx.
  src/include/catalog/schema.h
Labels: bug, ready-for-review

#41 Fixed bug in table page due to comparison with difference between unsigned ints
  src/storage/page/table_page.cpp
Labels: bug

#43 Added logging tests
  src/include/common/bustub_instance.h
  test/recovery/recovery_test.cpp
Labels: class-project, ready-to-merge

#44 Initialise global variable in Disk Manager Constructor
  src/storage/disk/disk_manager.cpp
Labels: bug

#45 Explicitly zero out the tuple's data on construction.
  src/storage/table/tuple.cpp
Labels: bug, class-project
