Repository cmu-db/bustub, pull requests merged in 2019-09, with the labels that each got.

#2 Add Docker image, add CI checks, fix CI issues.
  .dockerignore
  .travis.yml
  CMakeLists.txt
  Dockerfile
  build_support/packages.sh
  src/include/common/config.h
  test/CMakeLists.txt
Labels: infrastructure, ready-to-merge

#4 Change to frame_id_t, and fix buffer_pool_manager sample test
  src/buffer/buffer_pool_manager.cpp
  src/include/buffer/buffer_pool_manager.h
  test/buffer/buffer_pool_manager_test.cpp
Labels: bug

#1 Reintroduce buffer pool manager callbacks for grading purposes.
  src/buffer/buffer_pool_manager.cpp
  src/include/buffer/buffer_pool_manager.h
Labels: feature, ready-for-review

#8 Update README w/ Linux/Mac info
  README.md
Labels: ready-for-review

#7 Fix check-format
  test/buffer/buffer_pool_manager_test.cpp
Labels: best-practice, ready-for-review

#11 Format clock_replacer_test
  test/buffer/clock_replacer_test.cpp
Labels: best-practice

#12 NOLINT <thread> in clock_replacer_test
  test/buffer/clock_replacer_test.cpp
Labels: best-practice

#6 Add the CircleCI config file
  .circleci/config.yml
Labels: in-progress, infrastructure

#10 Enable ASAN on Debug builds and update README.md.
  CMakeLists.txt
  README.md
  test/container/hash_table_test.cpp
Labels: bug, feature

#13 Added instructions for Windows
  README.md
Labels: best-practice

#16 Fix clang-tidy in header files used for grading
  src/common/util/string_util.cpp
  src/include/catalog/column.h
  src/include/storage/disk/disk_manager.h
  src/include/type/integer_parent_type.h
  src/include/type/value_factory.h
  src/storage/page/header_page.cpp
  src/type/timestamp_type.cpp
Labels: best-practice

#21 Favor constexpr over const
  src/include/type/limits.h
Labels: best-practice

#20 Convert #define to constexpr
  src/include/common/config.h
  src/include/common/logger.h
  src/include/storage/page/table_page.h
  src/include/type/limits.h
Labels: best-practice

#23 Fix the memory leak in the sample buffer pool test.
  src/include/catalog/column.h
  src/include/common/config.h
  src/include/type/value_factory.h
  test/buffer/buffer_pool_manager_test.cpp
Labels: bug

#25 Apply naming conventions from Terrier
  .clang-tidy
  src/common/config.cpp
  src/common/util/string_util.cpp
  src/concurrency/lock_manager.cpp
  src/concurrency/transaction_manager.cpp
  src/include/common/config.h
  src/include/common/exception.h
  src/include/common/logger.h
  src/include/common/rwlatch.h
  src/include/concurrency/transaction_manager.h
  src/include/storage/index/generic_key.h
  src/include/storage/table/table_heap.h
  src/include/type/timestamp_type.h
  src/include/type/type.h
  src/include/type/value.h
  src/include/type/value_factory.h
  src/storage/page/table_page.cpp
  src/storage/table/table_heap.cpp
  src/storage/table/table_iterator.cpp
  src/type/bigint_type.cpp
  src/type/boolean_type.cpp
  src/type/decimal_type.cpp
  src/type/integer_type.cpp
  src/type/smallint_type.cpp
  src/type/timestamp_type.cpp
  src/type/tinyint_type.cpp
  src/type/type.cpp
  src/type/value.cpp
  src/type/varlen_type.cpp
  test/concurrency/lock_manager_test.cpp
  test/table/tuple_test.cpp
  test/type/type_test.cpp
Labels: best-practice

#29 Linear Probe Hash Table Starter Code
  src/container/hash/linear_probe_hash_table.cpp
  src/include/container/hash/hash_function.h
  src/include/container/hash/hash_table.h
  src/include/container/hash/linear_probe_hash_table.h
  src/include/storage/disk/disk_manager.h
  src/include/storage/index/index.h
  src/include/storage/index/int_comparator.h
  src/include/storage/index/linear_probe_hash_table_index.h
  src/include/storage/page/hash_table_block_page.h
  src/include/storage/page/hash_table_header_page.h
  src/include/storage/page/hash_table_page_defs.h
  src/include/storage/page/header_page.h
  src/storage/disk/disk_manager.cpp
  src/storage/index/linear_probe_hash_table_index.cpp
  src/storage/page/hash_table_block_page.cpp
  src/storage/page/hash_table_header_page.cpp
  src/storage/page/header_page.cpp
  test/container/hash_table_page_test.cpp
  test/container/hash_table_test.cpp
  test/table/header_page_test.cpp
Labels: class-project
