Repository cmu-db/bustub, pull requests merged in 2020-11, with the labels that each got.

#118 fix bug in BPLUSTREE_TYPE::ToGraph
  src/storage/index/b_plus_tree.cpp
Labels: bug

#113 Use memcpy and memcmp for BinaryDataTest in BufferPoolManagerTest.
  test/buffer/buffer_pool_manager_test.cpp
Labels: best-practice, bug

#110 ignore vagrant configuration directory
  .gitignore
Labels: best-practice, infrastructure
